[package]
name = "rediblaster-rs"
version = "0.1.0"
authors = ["mautomic <maurya373@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.17.0"
rand = "0.7.3"